# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('falla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Afectados', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('report', models.CharField(max_length=100, verbose_name='Reportado')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.Department', verbose_name='Departmento')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falla.Falla', verbose_name='Tipo de Falla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
