# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='solventado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='Afectados',
            field=models.IntegerField(default=0, verbose_name='Usuarios afectados'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='fin',
            field=models.DateTimeField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='inicio',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='report',
            field=models.CharField(max_length=100, verbose_name='Reportado a'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
    ]
