# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimientos', '0002_auto_20160703_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientos',
            name='solucion',
            field=models.TextField(default='', max_length=200, verbose_name='Describa la solucion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion de la falla'),
        ),
    ]
